name: CitiTrader
main:  me.tehbeard.cititrader.CitiTrader
version: BETA-2.0
depend: [Citizens,Vault]
softdepend: [Towny]
commands:
    trader:
        aliases: ctrader
        description: CitiTrader commands 
        usage: |
          /<command> create name -type [TYPE] - Create a trader at the players current location
          /<command> fire - fire an npc
          /<command> setwallet [private|owner|bank|admin] accountname - set wallet type
          /<command> wallet [give|take] amount  - place/remove money from a private wallet
          /<command> sellprice price - Set selling price for item currently in hand, right click npc to set price for them.
          /<command> buyprice price - Set buying price for item currently in hand, right click npc to set price for them.
          /<command> cancel - Cancels all traders status with player
          /<command> reloadprofiles - reload all profiles
permissions:
  traders.command.*:
    description: Grants access to all trader commands
    default: op
    children:
      traders.command.create: true
      traders.command.sellprice: true
      traders.command.buyprice: true
      traders.command.fire: true
      traders.command.cancel: true
      traders.command.reloadprofiles: true
      traders.command.setwallet: true
      traders.command.wallet: true
      traders.command.linkchest: true
      traders.command.unlinkchest: true
      traders.command.link: true
      traders.command.unlink: true
  traders.wallet.*:
    description: Grants access to all wallet commands
    default: op
    children:
      traders.wallet.admin: true
      traders.wallet.private: true
      traders.wallet.owner: true
      traders.wallet.town_bank: true
      traders.wallet.bank: true
  traders.command.cancel:
    description: Can use cancel command
    default: true
  traders.command.reloadprofiles:
    description: Can reload profiles
    default: op
  traders.command.create:
    description: Can create traders using /trader create
    default: op
  traders.command.sellprice:
    description: can set sale prices of traders
    default: op
  traders.command.buyprice:
    description: Can set purchase orders
    default: op
  traders.command.setwallet:
    description: Set an npc's wallet type
    default: op
  traders.command.wallet:
    description: Give/take from an npc wallet.
    default: op
  traders.command.link:
    description: Link two NPCs price lists
    default: op
  traders.command.unlink:
    description: Unlink to NPCs price lists
    default: op
  traders.command.linkchest:
    description: Link a chest to an NPC
    default: true
  traders.command.unlinkchest:
    description: Unlink a chest from an NPC
    default: true
  traders.wallet.private:
    description: Allows user to set traders to use their own private wallet.
    default: true
  traders.wallet.owner:
    description: Allows user to set traders to use their owner's bank wallet.
    default: true  
  traders.wallet.bank:
    description: Allows user to set traders to use a bank account (ECONOMY PLUGIN MUST SUPPORT BANKS, USER MUST OWN BANK ACCOUNT).
    default: true
  traders.wallet.town_bank:
    description: Allows user to set the traders to use a town bank (TOWNY PLUGIN MUST BE INSTALLED)
    default: true
  traders.wallet.admin:
    description: Allows user to set traders to use a bank account (ECONOMY PLUGIN MUST SUPPORT BANKS, USER MUST OWN BANK ACCOUNT).
    default: op